== Kubectl

. `kubectl` relies on a config file located at `$HOME/.kube/config`
.. Cotains - target cluster name and credentails for the cluster

How `kubectl` works?

. When administrator invoke a `kubectl` command, it is translated into an API call and sends this to `kube-apiserver` in cluster master serve through `https`.
. The `kube-apiserver` processes the request quering `etcd` and send API response through `https` to `kubectl`.
. `kubectl` translates the API and displays results to the screen. 

`kubectl    [command]    [type]    [name]    [flags]`


```
$ kubectl config view

```

== Pods Status

. Pending
. Running
. Succeeded - all the containers have be completed running sucessfully and those will not be restarted. 
. Failed
. UNKNOWN - state of the pods can not be retrieved. 
. CrashLoopBackOff - One of the containers in the pod exited unexpectedly after restarting at least once. 


```  
$ kubectl logs -l run=nginx-app
$ kubectl get po
$ kubectl describe po nginx-app-9b58d8df5-2xxbs
$ kubectl logs po nginx-app-9b58d8df5-2xxbs
$ kubectl logs nginx-app-9b58d8df5-2xxbs
$ kubectl exec nginx-app-9b58d8df5-2xxbs whoami
$ kubectl exec nginx-app-9b58d8df5-2xxbs ls /
$ kubectl exec -it nginx-app-9b58d8df5-2xxbs  -- /bin/bash
```

== Build GKE Cluster

```
$ export  my_zone=us-central1-a
$ export my_cluster=standard-cluster-1
$ gcloud container clusters create $my_cluster --num-nodes 3 --zone $my_zone --enable-ip-alias
```

https://cloud.google.com/sdk/gcloud/reference/container/clusters/create

== Authenticate with the GKE Cluster

```
# gcloud container clusters get-credentials your-first-cluster-1 --zone us-central1-a --project <gcp_project_name>
```

== Scale Up and Down Cluster
For scaling up and down a GKE cluster use the following command. 

```
# gcloud container clusters resize your-first-cluster-1 --zone us-central1-a --node-pool pool-1 --size 4
```

== Upgrade Cluster

```
# gcloud container get-server-config [show available gke versions]
# gcloud container clusters upgrade your-first-cluster-1 --master --cluster-version 1.13.7-gke.8 [upgrade master]
# gcloud container clusters upgrade your-first-cluster-1 [upgrade nodes]
# gcloud container node-pools update pool-1 --cluster your-first-cluster-1 --enable-autoupgrade [enable auto upgrade]
# gcloud container node-pools update pool-1 --cluster your-first-cluster-1 --no-enable-autoupgrade [disable auto upgrade]
# gcloud container clusters delete your-first-cluster-1
```
== Get the Current Namespace

```
$ kubectl config current-context
$ kubectl config set-context `kubectl config current-context` --namespace develop
$ kubectl get sa default -o jsonpath='{.metadata.namespace}'
```

== Deploy Kubernetes Application - Simple

In the following example we will configure the Nginx app to run in the GKE cluster. 
```
# kubectl run nginx-app --image marketplace.gcr.io/google/nginx1:1.14
# kubectl scale deployment --replicas 4 nginx-app
# kubectl get po -o wide
# kubectl get deployments -o wide
# kubectl expose deployment nginx-app --port 80 --type=LoadBalancer
# kubectl get svc
# kubectl set image deployment nginx-app nginx-app=marketplace.gcr.io/google/nginx1:1.15
```
=== Build and Deployment Application 

The following GH repository is part of Linux Academy GKE deep dive course. 

`https://github.com/BPalmerLA/GoogleKubernetes/`

```
# docker build -t nginx-app .
# docker tag nginx-app gcr.io/<gcp_project>/nginx-app:v1
# gcloud auth configure-docker
# docker push gcr.io/<gcp_project>/nginx-app:v1
# gcloud container images list
# kubectl run nginx-app-production --image gcr.io/<gcp_project>/nginx-app:v1
# kubectl scale deployment --replicas 5 nginx-app-production
# kubectl expose deployment nginx-app-production --port 80 --type=LoadBalancer
```
=== Scale Up and Down Applications
Use the scale to scale up or down an application. Alternatively export the deployments to a file, edit the configurations and apply it.

```
# kubectl scale deployments --replicas 5 nginx-app     OR
# kubectl get deployment nginx-app-production -o yaml >> nginx-app-production.yaml
# kubectl apply -f nginx-app-production.yaml              OR
# kubectl autoscale deployment nginx-app-production --cpu-percent=1 --min=13 --max=25
```
